language: c
 
install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null
  - mozroots --import --sync
  - mv -f ./.nuget/NuGet.mono.targets ./.nuget/NuGet.targets
  - chmod +x ./xunit/xunit.console.clr4.x86.exe
  - export EnableNuGetPackageRestore=true  
 
script:
  - xbuild ./C-Sharp-Promise.sln
  - mono ./xunit/xunit.console.clr4.x86.exe ./bin/Debug/RSG.Promise.Tests.dll